#%RAML 1.0
title: CoffAPI
version: v1
baseUri: http://api.coffapi.com/v1

schemas:
   song: |


/beans:
  description: A comprehensive listing of coffee bean types
  get:
    description: Get a list of coffee beans based on name
    queryParameters:
      beanProductName:
        description : "Name of the bean product from the manufacturer"
        required    : false
        minLength   : 3
        type        : string
        example     : "Espresso Dark Roast Arabica USDA Organic"
      beanOrganic:
        description : "Indication as to whether this specific bean product is USDA Organic"
        required    : false
        type        : boolean
        example     : true
      beanDecaf:
        description : "Indication as to whether this specific bean product is decaffeinated"
        required    : false
        type        : boolean
        example     : false
    responses:
      200:
        body:
          application/json:
            example: |
              "beans": [
                  { "beanProductID"     : "001",
                    "beanProductName"   : "Espresso Dark Roast Arabica USDA Organic",
                    "beanSpecies"       : "Arabica",
                    "beanOriginRegion"  : "Latin America",
                    "beanOriginCountry" : "Guatemala",
                    "beanRoastDepth"    : "Dark",
                    "beanBrand"         : "Java Planet",
                    "beanOrganic"       : true,
                    "beanFairTrade"     : true,
                    "beanDecaf"         : false,
                    "beanIdealDrinks"   : [
                        { "drinkID"     : "505",
                          "drinkName"   : "Espresso Romano",
                          "drinkFamily" : "Black Espresso",
                          "drinkBlurb"  : "An espresso Romano is a shot of espresso with a slice of lemon served on the side. The lemon can be run along the rim of the cup as a way to accentuate the espresso's sweetness.",
                          "drinkHotCold": "Hot",
                          "drinkWikiURL": "https://en.wikipedia.org/wiki/List_of_coffee_drink#Espresso_Romano"
                        },
                        { "drinkID"     : "507",
                          "drinkName"   : "Ristretto",
                          "drinkFamily" : "Black Espresso",
                          "drinkBlurb"  : "Ristretto is traditionally a short shot of espresso made with the normal amount of ground coffee but extracted with about half the amount of water.",
                          "drinkHotCold": "Hot",
                          "drinkWikiURL": "https://en.wikipedia.org/wiki/List_of_coffee_drinks#Ristretto"
                        }
                    ]
                  },
                  {
                    "beanProductID"     : "002",
                    "beanProductName"   : "Espresso Dark Roast Arabica USDA Organic Decaf",
                    "beanSpecies"       : "Arabica",
                    "beanOriginRegion"  : "Latin America",
                    "beanOriginCountry" : "Guatemala",
                    "beanRoastDepth"    : "Dark",
                    "beanBrand"         : "Java Planet",
                    "beanOrganic"       : true,
                    "beanFairTrade"     : true,
                    "beanDecaf"         : true,
                    "beanIdealDrinks"   : [
                            { "drinkID"     : "519",
                              "drinkName"   : "Macchiato",
                              "drinkFamily" : "Milked Espresso",
                              "drinkBlurb"  : "A caffè macchiato Macchiato, meaning stained, is an espresso with a dash of foamed milk. At first sight it resembles a small cappuccino, but even if the ingredients are the same as those used for cappuccino, a macchiato has a much stronger and aromatic taste. The milk is foamed directly into the espresso cup, which is then put under the coffee outlet. The espresso is then drawn into the cup.",
                              "drinkHotCold": "Hot",
                              "drinkWikiURL": "https://en.wikipedia.org/wiki/List_of_coffee_drinks#Macchiato"
                            },
                            { "drinkID"     : "520",
                              "drinkName"   : "Espresso Vienna",
                              "drinkFamily" : "Milked Espresso",
                              "drinkBlurb"  : "Also known as Melange, espresso Vienna is popular in Austria, Switzerland and the Netherlands, and is traditionally similar to latte and cappuccino (and more a mix of the two), a large cup with espresso and steamed milk with some milk foam.",
                              "drinkHotCold": "Hot",
                              "drinkWikiURL": "https://en.wikipedia.org/wiki/List_of_coffee_drinks#Vienna_coffee"
                            }
                    ]
                  },
                  {
                    "beanProductID"     : "003",
                    "beanProductName"   : "Brazil Peaberry",
                    "beanSpecies"       : "Arabica",
                    "beanOriginRegion"  : "Latin America",
                    "beanOriginCountry" : "Brazil",
                    "beanRoastDepth"    : "Medium",
                    "beanBrand"         : "Rising Sun",
                    "beanOrganic"       : false,
                    "beanFairTrade"     : false,
                    "beanDecaf"         : false,
                    "beanIdealDrinks"   : [
                            { "drinkID"     : "508",
                              "drinkName"   : "Antonccino",
                              "drinkFamily" : "Milked Espresso",
                              "drinkBlurb"  : "An antoccino is a single shot of espresso with steamed milk in a 1:1 ratio, served in an espresso cup.",
                              "drinkHotCold": "Hot",
                              "drinkWikiURL": "https://en.wikipedia.org/wiki/List_of_coffee_drinks#Antoccino"
                            },
                            { "drinkID"     : "509",
                              "drinkName"   : "Breve",
                              "drinkFamily" : "Milked Espresso",
                              "drinkBlurb"  : "Espresso made with a steamed mixture of half milk and half cream (i.e., half and half).",
                              "drinkHotCold": "Hot",
                              "drinkWikiURL": "https://en.wikipedia.org/wiki/List_of_coffee_drinks#Breve"
                            }
                    ]
                  },
                  ]
